//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant1_Mozaika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSuppliers
    {
        public int MaterialSupplierID { get; set; }
        public int MaterialID { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
