//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant1_Mozaika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.MaterialSuppliers = new HashSet<MaterialSuppliers>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public int MaterialTypeID { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal StockQuantity { get; set; }
        public decimal MinimumQuantity { get; set; }
        public decimal PackageQuantity { get; set; }
        public int UnitID { get; set; }
    
        public virtual MaterialTypes MaterialTypes { get; set; }
        public virtual ICollection<MaterialSuppliers> MaterialSuppliers { get; set; }
        public virtual Units Units { get; set; }

        public class MaterialViewModel
        {
            public int MaterialID { get; set; }
            public string MaterialName { get; set; }
            public string MaterialTypeName { get; set; }
            public decimal UnitPrice { get; set; }
            public decimal StockQuantity { get; set; }
            public decimal MinimumQuantity { get; set; }
            public decimal PackageQuantity { get; set; }
            public string UnitName { get; set; }
            public decimal BatchCost { get; set; }
        }

    }
}
