//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant1_Mozaika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.MaterialSuppliers = new HashSet<MaterialSuppliers>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public int SupplierTypeID { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual ICollection<MaterialSuppliers> MaterialSuppliers { get; set; }
        public virtual SupplierTypes SupplierTypes { get; set; }

        public class SupplierViewModel
        {
            public string SupplierName { get; set; }
            public int Rating { get; set; }
            public DateTime StartDate { get; set; }
        }
    }
}
