//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant1_Mozaika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTypes
    {
        public SupplierTypes()
        {
            this.Suppliers = new HashSet<Suppliers>();
        }
    
        public int SupplierTypeID { get; set; }
        public string SupplierTypeName { get; set; }
    
        public virtual ICollection<Suppliers> Suppliers { get; set; }
    }
}
